services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sebas
      - MONGO_INITDB_ROOT_PASSWORD=1234567890
    volumes:
      - mongodata:/data/db
volumes:
   mongodata: